version: "3.5"
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    hostname: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ${PWD}/setup/mosquitto/:/mosquitto/config/
    networks:
      - default

  mailhog:
    image: mailhog/mailhog
    hostname: mailhog
    command: ["-smtp-bind-addr", "0.0.0.0:25"]
    user: root
    expose:
      - 25
      - 8025
    ports:
      - "8026:25"
      - "8025:8025"
    healthcheck:
      test: echo | telnet 127.0.0.1 25
    networks:
      - default

  jj-smarthome-job:
    container_name: jj-smarthome-job
    build:
      context: .
      dockerfile: ./src/JJ.SmartHome.Job/Dockerfile
    networks:
      - default
    environment:
      - MQTT__URI=mosquitto
      - MQTT__User=
      - MQTT__Password=
      - Alerts__OccupancyTopic=zigbee2mqtt/hall_occupancy
      - SMTP__Host=mailhog
      - SMTP__Port=25
      - SMTP__Ssl=false
      - SMTP__User=
      - SMTP__Password=
      - SMTP__Sender=jj-smarthome@development.com
      - SMTP__NotificationAddresses__0=jj-smarthome@receiver.com
      - SnoozePeriodAfterAlerting=00:01:00

networks:
  default: