homeassistant: false
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://mosquitto:1883'
  #user: mosquitto
  # Optional: MQTT server authentication password (default: nothing)
  #password: my_password
  # Optional: MQTT client ID (default: nothing)
  client_id: jj-smarthome-z2m
  # Optional: Include device information to mqtt messages (default: false)
  include_device_information: true
frontend:
  port: 8899
serial:
  port: /dev/ttyACM0
  disable_led: true
devices: devices.yaml
