version: "3.8"
services:
  jj-smarthome-job:
    image: jj-smarthome-job
    restart: always
    build:
      context: ../
      dockerfile: ./src/JJ.SmartHome.Job/arm.Dockerfile
    networks:
      - default
    environment:
      - MQTT__URI=mosquitto
      - MQTT__Port=1883
      - MQTT__User=
      - MQTT__Password=
      - MQTT__Secure=false
      - SMTP__Host=${SMTP__Host}
      - SMTP__Port=${SMTP__Port}
      - SMTP__Ssl=${SMTP__Ssl}
      - SMTP__User=${SMTP__User}
      - SMTP__Password=${SMTP__Password}
      - SMTP__Sender=${SMTP__Sender}
      - SMTP__NotificationAddresses__0=${SMTP__NotificationAddresses__0}
      - SnoozePeriodAfterAlerting=${SnoozePeriodAfterAlerting}
      - InfluxDB__Uri=http://influxdb:9999
      - InfluxDB__User=${InfluxDB__User}
      - InfluxDB__Password=${InfluxDB__Password}
      - InfluxDB__Token=${InfluxDB__Token}
  
  jj-smarthome-sensehat:
    image: jj-smarthome-sensehat
    restart: always
    build:
      context: ../
      dockerfile: ./src/jj-smarthome-sensehat/Dockerfile
    networks:
      - default
    environment:
      - MQTT_URI=mqtt://mosquitto:1883
      
networks:
  default:
