version: "3.8"
services:
  jj-smarthome-job-tests:
    image: jj-smarthome-job-tests
    build:
      context: ../
      dockerfile: ./src/JJ.SmartHome.Job/Dockerfile
      target: test
    command: > 
        bash -c "sleep 15 && dotnet test --no-restore -c Release"
    networks:
      - default
    environment:
      - MQTT__URI=mosquitto
      - MQTT__Port=1883
      - MQTT__User=
      - MQTT__Password=
      - MQTT__Secure=false
      - SMTP__Host=mailhog
      - SMTP__Port=25
      - SMTP__Ssl=false
      - SMTP__User=
      - SMTP__Password=
      - SMTP__Sender=test@test.tst
      - SMTP__NotificationAddresses__0=notification@test.tst
      - InfluxDB__Uri=http://influxdb_v1:8086
      - InfluxDB__User=${InfluxDB__User}
      - InfluxDB__Password=${InfluxDB__Password}
      - InfluxDB__Token=${InfluxDB__Token}

networks:
  default: