version: "3.8"
services:
  jj-smarthome-job:
    image: jj-smarthome-job
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ./src/JJ.SmartHome.Job/arm.Dockerfile
    networks:
      - default
    environment:
      - MQTT__URI=${MQTT__URI:-mosquitto}
      - MQTT__Port=${MQTT__Port:-1883}
      - MQTT__User=
      - MQTT__Password=
      - MQTT__Secure=false
      - SMTP__Host=${SMTP__Host}
      - SMTP__Port=${SMTP__Port}
      - SMTP__Ssl=${SMTP__Ssl}
      - SMTP__User=${SMTP__User}
      - SMTP__Password=${SMTP__Password}
      - SMTP__Sender=${SMTP__Sender}
      - SMTP__NotificationAddresses__0=${SMTP__NotificationAddresses__0}
      - SnoozePeriodAfterAlerting=${SnoozePeriodAfterAlerting}
      - InfluxDB__Uri=${InfluxDB__Uri:-http://influxdb:8086}
      - InfluxDB__User=${InfluxDB__User}
      - InfluxDB__Password=${InfluxDB__Password}
      - InfluxDB__Token=${InfluxDB__Token}
  
  jj-smarthome-sensehat:
    image: jj-smarthome-sensehat
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ./src/jj-smarthome-sensehat/Dockerfile
    privileged: true
    networks:
      - default
    environment:
      - MQTT_URI=mqtt://mosquitto:1883
      - MQTT_URI=${MQTT_FULL_URI:-mqtt://mosquitto:1883}
networks:
  default:
