version: "3.8"
services:
  jj-smarthome-webapi:
    volumes:
      - ${PWD}/jj-smarthome/devices.sample.json:/app/devices.json

  jj-smarthome-sensehat:
    privileged: false
    environment:
      - MQTT_URI=${MQTT_FULL_URI:-mqtt://mosquitto:1883}
      - MODE=${SENSE_HAT_MODE:-simulator}
      - SERVER_URI=ws://jj-ws-server:8080
      - DEVICE=jj-smarthome-sensehat
  
  jj-ws-server:
    container_name: jj-ws-server
    image: jj-ws-server
    build:
      context: ../
      dockerfile: ./src/jj-smarthome-sensehat/Dockerfile
    command: ["npm", "run", "simulator-ws-serve"]
    expose:
      - "8080"
      - "4443"
    ports:
      - "8080:8080"
      - "4443:4443"
    networks:
      - default

networks:
  default: