version: "3.5"
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
      - ${PWD}/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always
    networks:
      - default
    privileged: true
    environment:
      - TZ=Europe/Amsterdam
      
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: always
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ${PWD}/mosquitto/:/mosquitto/config/
    networks:
      - default

  jj-smarthome-job:
    container_name: jj-smarthome-job
    image: jj-smarthome-job
    restart: always
    build:
      context: ../
      dockerfile: ./src/JJ.SmartHome.Job/arm.Dockerfile
    networks:
      - default
    environment:
      - MQTT__URI=mosquitto
      - MQTT__Port=1883
      - MQTT__User=
      - MQTT__Password=
      - MQTT__Secure=false
      - Alerts__OccupancyTopic=zigbee2mqtt/hall_occupancy
      - SMTP__Host=${SMTP__Host}
      - SMTP__Port=${SMTP__Port}
      - SMTP__Ssl=${SMTP__Ssl}
      - SMTP__User=${SMTP__User}
      - SMTP__Password=${SMTP__Password}
      - SMTP__Sender=${SMTP__Sender}
      - SMTP__NotificationAddresses__0=${SMTP__NotificationAddresses__0}
      - SnoozePeriodAfterAlerting=${SnoozePeriodAfterAlerting}
  
  jj-smarthome-sensehat:
    container_name: jj-smarthome-sensehat
    build:
      context: ../
      dockerfile: ./src/jj-smarthome-sensehat/Dockerfile
    restart: always
    networks:
      - default
    environment:
      - MQTT__URI=mqtt://mosquitto:1883
      
networks:
  default:
