version: "3.8"
services:
  mailhog:
    image: mailhog/mailhog
    command: ["-smtp-bind-addr", "0.0.0.0:25"]
    user: root
    expose:
      - 25
      - 8025
    ports:
      - "8026:25"
      - "8025:8025"
    healthcheck:
      test: echo | telnet 127.0.0.1 25
    networks:
      - default